@baseUrl = http://localhost:3000/api/offre

### Test API Ping
GET {{baseUrl}}/

### Test API Ping
GET {{baseUrl}}/

### Test Research
POST {{baseUrl}}/search
content-type: application/json

{
    "research": "Zab"
}