@baseUrl = https://ucdp-backend.onrender.com/api/user

### Register 
POST http://localhost:3000/api/user/register
content-type: application/json

{
    "nom": "Boyer",
    "prenom": "Evan",
    "email": "evanboy@hotmail.frrr",
    "password": "Azertyuiop12345.",
    "telephone": "0987654321",
    "adresse": "Blabla ",
    "code_postal": "31100",
    "ville": "Toulouse",
    "raison_sciale": null,
    "role":"CLIENT"
}

### Login
GET http://localhost:3000/api/logs